### PR TITLE
Added profile

### PR DESCRIPTION
**Pull request by alexdeathway**
Added  profile which can be seen by user by visiting /profile (Modification required ).

### CODE REVIEW

**Comment by niteshsinha17** [comment]
Great,
But right now its not needed. It will be added soon.Design is being made for this. If you wish then you can continue it later through this PR. Thanks

**Comment by alexdeathway** [comment]
ok Fine

**Comment by niteshsinha17** [comment]
@alexdeathway  I have opened an Issue https://github.com/niteshsinha17/GameZilla/issues/11 for it. 
You can continue your work from here. Please also read the contribution guideline present in the readme. Also, you will need to rebase this PR. Other Issues are also opened which is related to the profile.  If you wish you can work on them too
Feel free to ask your query. Thank you.

**Comment by alexdeathway** [comment]
I will prefer to work from the start for profile model.

**Comment by niteshsinha17** [comment]
Okay. So you just need to create profile model and you have show the profile details on a template without styling. Styling will be handled in another pr

**Comment by alexdeathway** [comment]
fine, then closing this pr.

**Comment by niteshsinha17** [comment]
You closed it unnecessarily. Actually, there are different issues related to the profile. 

> Okay. So you just need to create profile model and you have show the profile details on a template without styling

This is one of them. You can reopen this PR by pushing into it.

**Comment by alexdeathway** [comment]
okay.

**Comment by alexdeathway** [comment]
this pr have some conflicts, working fresh for profile is more reasonable

**Comment by niteshsinha17** [comment]
If you want work from fresh then go ahead. I have no problem. But please inform what will be more flexible for you then I will reopen this issue.

**Pull request closed without merging**
